### ISSUE TITLE
请问下论文中测试集的使用

### ISSUE THREAD

**Issue by sparklejojo** [Chasel-Tsui/mmdet-aitod#13]
目前看到很多论文的实验设置描述都是训练时的train在trainval set上，测试时在Test set上
想问下具体的细节，是哪一种呢？
①训练时train在trainval set，val在Test set，没有另外的Test步骤
②训练时train在trainval set，val在val set，另外加测试步骤在Test set上

**Comment by Chasel-Tsui** [comment]
比较合理的方法是在trainval上训练，test验证和测试，现在论文里汇报的也是这种设置下的结果。但是test set比较大，在训练过程用于验证会耗费比较久的时间，如果训练过程中需要快速验证，也可以使用val set验证下模型精度

**Comment by sparklejojo** [comment]
明白了谢谢！
